# Define compiler and flags
CXX := g++
CXXFLAGS := -Wall -g -Iinclude

# Define libraries to link against
LIBS := -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf

# Define the output executable and source files
TARGET := prog1
SRCS := src/editor.cpp

# Dependency files generated by g++
DEPS := $(OBJS:.o=.d)

# Define the default build target
all: $(TARGET)

# Rule to build the target
$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET) $(LIBS)

# Rule to compile .cpp files into .o files and generate .d dependency files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include automatically generated dependency files
-include $(DEPS)

# Rule to clean up the build
clean:
	rm -f $(TARGET)

# Optional: Add .PHONY to prevent conflicts with files named 'clean' or 'all'
.PHONY: all clean
