# Define compiler and flags
CXX := g++
CXXFLAGS := -std=c++17 -Wall -g -I"C:/MinGW/Include" -Iinclude -DSDL_MAIN_HANDLED

# Define libraries to link against
LIBS := -lmingw32 -lSDL2_ttf -lSDL2main -lSDL2

# Define the output executable and source files
SRCS := src/main.cpp src/cursor.cpp src/editor.cpp src/renderer.cpp
TARGET := prog

# # Dependency files generated by g++
# DEPS := $(OBJS:.o=.d)

# Define the default build target
all: $(TARGET)

# Rule to build the target
$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET) $(LIBS)

# # Rule to compile .cpp files into .o files and generate .d dependency files
# %.o: %.cpp
# 	$(CXX) $(CXXFLAGS) -c $< -o $@

# # Include automatically generated dependency files
# -include $(DEPS)

# Rule to clean up the build
clean:
	rm -f $(TARGET)

# Optional: Add .PHONY to prevent conflicts with files named 'clean' or 'all'
.PHONY: all clean
