name: Ctextor CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-ttf-dev cppcheck

    - name: Build project
      run: make

    - name: Run tests
      run: make test

    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 src/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ctextor-build
        path: |
          prog
          test_prog
